# Generated by Django 4.1.7 on 2023-09-01 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linkop', '0003_mutualinterest'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mutualinterest',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='mutualinterest',
            name='user1',
        ),
        migrations.RemoveField(
            model_name='mutualinterest',
            name='user2',
        ),
        migrations.DeleteModel(
            name='Interest',
        ),
        migrations.DeleteModel(
            name='MutualInterest',
        ),
    ]
