# Generated by Django 4.1.7 on 2023-09-01 09:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkop', '0005_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='returned_interests',
            field=models.ManyToManyField(blank=True, related_name='received_interests', to=settings.AUTH_USER_MODEL),
        ),
    ]
