# Generated by Django 4.1.7 on 2023-09-02 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linkop', '0007_notification_sender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='returned_interests',
        ),
    ]
