# Generated by Django 4.1.7 on 2023-09-06 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkop', '0008_remove_customuser_returned_interests'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_past_event',
            field=models.BooleanField(default=False),
        ),
    ]
