# Generated by Django 5.0 on 2023-12-16 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linkop', '0009_event_is_past_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='name',
        ),
    ]
