# Generated by Django 5.0.2 on 2024-02-16 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkop', '0010_remove_customuser_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_updated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='mediafiles/user_photos/'),
        ),
    ]
